version: "3"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  highscore-server:
    build: Api/
    image: vonramen/highscoreserver:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
     - mongo
    networks:
     - backend


networks:
  backend: