version: "3"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodbdata:/data/db

  highscore-server:
    build: Api/
    image: vonramen/highscoreserver:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
     - mongo
    networks:
     - backend


networks:
  backend:

volumes:
  mongodbdata: